In [1]:
import numpy as np

In [2]:
a = np.logspace(1, 10, 10)

In [3]:
a

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [4]:
x, y = np.mgrid[0:5, 0:5]

In [5]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [6]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [7]:
[(xs, ys) for xs, ys in zip(x, y)]

[(array([0, 0, 0, 0, 0]), array([0, 1, 2, 3, 4])),
 (array([1, 1, 1, 1, 1]), array([0, 1, 2, 3, 4])),
 (array([2, 2, 2, 2, 2]), array([0, 1, 2, 3, 4])),
 (array([3, 3, 3, 3, 3]), array([0, 1, 2, 3, 4])),
 (array([4, 4, 4, 4, 4]), array([0, 1, 2, 3, 4]))]

In [8]:
list(map(lambda lst1,lst2: [(xs, ys) for xs, ys in zip(lst1, lst2)], x, y))

[[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4)],
 [(1, 0), (1, 1), (1, 2), (1, 3), (1, 4)],
 [(2, 0), (2, 1), (2, 2), (2, 3), (2, 4)],
 [(3, 0), (3, 1), (3, 2), (3, 3), (3, 4)],
 [(4, 0), (4, 1), (4, 2), (4, 3), (4, 4)]]

In [9]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [11]:
np.diag([1, 2, 3], k = 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [12]:
arr_3d = np.random.rand(2,3,4)

In [13]:
arr_3d

array([[[0.22703944, 0.59254809, 0.87743544, 0.26559949],
        [0.09799126, 0.66407928, 0.75621741, 0.96182895],
        [0.85776879, 0.20321788, 0.12143126, 0.830575  ]],

       [[0.8465519 , 0.7108761 , 0.80491262, 0.1472968 ],
        [0.66744666, 0.87971311, 0.30204073, 0.91391438],
        [0.36891901, 0.32414261, 0.10714834, 0.80263706]]])

In [14]:
arr_3d.itemsize

8

In [15]:
arr_3d.nbytes

192

In [16]:
arr_3d.ndim

3

In [17]:
arr_3d

array([[[0.22703944, 0.59254809, 0.87743544, 0.26559949],
        [0.09799126, 0.66407928, 0.75621741, 0.96182895],
        [0.85776879, 0.20321788, 0.12143126, 0.830575  ]],

       [[0.8465519 , 0.7108761 , 0.80491262, 0.1472968 ],
        [0.66744666, 0.87971311, 0.30204073, 0.91391438],
        [0.36891901, 0.32414261, 0.10714834, 0.80263706]]])

In [18]:
arr_3d[1, 1, 2]

0.302040725862988

In [19]:
arr_3d[0, :, :]

array([[0.22703944, 0.59254809, 0.87743544, 0.26559949],
       [0.09799126, 0.66407928, 0.75621741, 0.96182895],
       [0.85776879, 0.20321788, 0.12143126, 0.830575  ]])

In [20]:
arr_3d[:, :2, 1:3]

array([[[0.59254809, 0.87743544],
        [0.66407928, 0.75621741]],

       [[0.7108761 , 0.80491262],
        [0.87971311, 0.30204073]]])

In [22]:
arr_3d[0, :, 1] = 1.0

In [23]:
arr_3d

array([[[0.22703944, 1.        , 0.87743544, 0.26559949],
        [0.09799126, 1.        , 0.75621741, 0.96182895],
        [0.85776879, 1.        , 0.12143126, 0.830575  ]],

       [[0.8465519 , 0.7108761 , 0.80491262, 0.1472968 ],
        [0.66744666, 0.87971311, 0.30204073, 0.91391438],
        [0.36891901, 0.32414261, 0.10714834, 0.80263706]]])

In [24]:
arr_3d[0, :, [False, True, True, False]]

array([[1.        , 1.        , 1.        ],
       [0.87743544, 0.75621741, 0.12143126]])

In [36]:
x = np.random.randn(3,2)

In [37]:
x

array([[-0.96612647,  0.19070793],
       [-0.2085682 ,  1.41930292],
       [ 0.7432659 ,  0.69098395]])

In [38]:
x > 0.5

array([[False, False],
       [False,  True],
       [ True,  True]])

In [39]:
np.where(x > 0.5)

(array([1, 2, 2], dtype=int64), array([1, 0, 1], dtype=int64))

In [40]:
v1 = np.arange(1, 5)

In [41]:
v1

array([1, 2, 3, 4])

In [42]:
v1.shape

(4,)

In [46]:
np.matrix(v1).shape

(1, 4)

In [52]:
v1.transpose()

array([1, 2, 3, 4])

In [54]:
mat = np.random.randint(78, 523, (3, 3))

In [55]:
mat

array([[294, 175, 276],
       [312, 108, 352],
       [233, 106, 317]])

In [56]:
np.linalg.det(mat)

-1677135.9999999984

In [57]:
np.mean(mat)

241.44444444444446

In [58]:
np.mean(mat, axis = 1)

array([248.33333333, 257.33333333, 218.66666667])

In [59]:
np.std(mat)

86.60524889290757

In [60]:
np.var(mat)

7500.469135802468

In [62]:
np.sin(mat)

array([[-0.96610999, -0.8011346 , -0.44408566],
       [-0.83179148,  0.92681851,  0.14114985],
       [ 0.49873928, -0.7271425 ,  0.29633979]])

In [63]:
np.max(mat)

352

In [64]:
np.argmax(mat)

5

In [65]:
np.max(mat, axis = 1)

array([294, 352, 317])

In [66]:
np.argmax(mat, axis = 1)

array([0, 2, 2], dtype=int64)

In [67]:
np.cumprod(mat)

array([        294,       51450,    14200200,   135495104,  1748569344,
        1316085760,  1705304064,   373604352, -1826504704], dtype=int32)

In [68]:
np.cumprod(mat, axis = 1)

array([[     294,    51450, 14200200],
       [     312,    33696, 11860992],
       [     233,    24698,  7829266]], dtype=int32)

In [69]:
np.cumsum(mat)

array([ 294,  469,  745, 1057, 1165, 1517, 1750, 1856, 2173], dtype=int32)

In [70]:
np.cumsum(mat, axis = 1)

array([[294, 469, 745],
       [312, 420, 772],
       [233, 339, 656]], dtype=int32)

In [71]:
mat

array([[294, 175, 276],
       [312, 108, 352],
       [233, 106, 317]])

In [72]:
np.trace(mat)

719

In [73]:
np.diag(mat)

array([294, 108, 317])

In [74]:
np.diag(mat).sum()

719

In [75]:
mat

array([[294, 175, 276],
       [312, 108, 352],
       [233, 106, 317]])

In [76]:
v9 = np.reshape(mat, (1,9))

In [77]:
v9

array([[294, 175, 276, 312, 108, 352, 233, 106, 317]])

In [79]:
mat.reshape(1, 9)

array([[294, 175, 276, 312, 108, 352, 233, 106, 317]])

In [80]:
mat.reshape(9, 1)

array([[294],
       [175],
       [276],
       [312],
       [108],
       [352],
       [233],
       [106],
       [317]])

In [82]:
v9[0] = 9999999 

In [84]:
mat

array([[9999999, 9999999, 9999999],
       [9999999, 9999999, 9999999],
       [9999999, 9999999, 9999999]])

In [85]:
mat

array([[9999999, 9999999, 9999999],
       [9999999, 9999999, 9999999],
       [9999999, 9999999, 9999999]])

In [88]:
mat.flatten()

array([9999999, 9999999, 9999999, 9999999, 9999999, 9999999, 9999999,
       9999999, 9999999])

In [89]:
mat

array([[9999999, 9999999, 9999999],
       [9999999, 9999999, 9999999],
       [9999999, 9999999, 9999999]])

In [98]:
mat_3d = mat[:,:,np.newaxis]

In [99]:
mat_3d

array([[[9999999],
        [9999999],
        [9999999]],

       [[9999999],
        [9999999],
        [9999999]],

       [[9999999],
        [9999999],
        [9999999]]])

In [100]:
mat

array([[9999999, 9999999, 9999999],
       [9999999, 9999999, 9999999],
       [9999999, 9999999, 9999999]])

In [102]:
mat_3d_2 = mat[np.newaxis,:,:]

In [103]:
mat_3d_2

array([[[9999999, 9999999, 9999999],
        [9999999, 9999999, 9999999],
        [9999999, 9999999, 9999999]]])

In [104]:
a = np.array([[1,2],[3,4]])

In [105]:
a

array([[1, 2],
       [3, 4]])

In [108]:
np.repeat(a, 2, axis = 1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [109]:
np.repeat(a, 2, axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [110]:
a

array([[1, 2],
       [3, 4]])

In [111]:
np.tile(a, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [114]:
a

array([[1, 2],
       [3, 4]])

In [116]:
np.vstack([a, a])

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [117]:
np.hstack([a, a])

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [120]:
np.concatenate([a, a], 0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [121]:
np.concatenate([a, a], axis = 1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])